CREATE TABLE budu.gt_pk_metadata (
  table_schema VARCHAR(32) NOT NULL,
  table_name VARCHAR(32) NOT NULL,
  pk_column VARCHAR(32) NOT NULL,
  pk_column_idx INTEGER,
  pk_policy VARCHAR(32),
  pk_sequence VARCHAR(64),
  unique (table_schema, table_name, pk_column),
  check (pk_policy in ('sequence', 'assigned', 'autogenerated'))
);

GRANT ALL PRIVILEGES ON TABLE budu.gt_pk_metadata TO gvsigonline;

 
 
create or replace view budu.v_tramo_calle_tv_fuente  as
  SELECT gid, geom, idcalle, c.nombre, tipo_vialidad_id, tv.nombre as tipo_vialidad, t.fuente_id, f.descripcion 
  FROM budu.tramo t
  left join budu.calle c on c.id = t.idcalle 
  left join budu.tipo_vialidad tv on tv.id = t.tipo_vialidad_id 
  left join budu.fuente f on t.fuente_id = f.id;

GRANT ALL PRIVILEGES ON budu.v_tramo_calle_tv_fuente TO gvsigonline;

INSERT INTO 
  budu.gt_pk_metadata( table_schema, table_name, pk_column, pk_column_idx, pk_policy, pk_sequence) 
 VALUES ('budu', 'v_tramo_calle_tv_fuente', 'gid', 1, 'assigned',  null);